// market/src/components/CardSelectGrid.jsx
import { createContext, useContext, useId, useLayoutEffect, useMemo } from 'react';
import { useSelectBand } from '../select-band.jsx';

const CardSelectContext = createContext(null);

export function useCardSelect() {
  return useContext(CardSelectContext);
}

/**
 * Marks a card grid for multi-select. Gesture listeners live in SelectBandProvider
 * (Chrome) so they stay warm across navigations — this registers `cards` into the
 * page-wide catalog so a drag pile can span every rail on the page.
 */
export default function CardSelectGrid({
  cards = [],
  className = 'grid',
  contents = false,
  children,
}) {
  const band = useSelectBand();
  const gridKey = useId();
  const ids = useMemo(
    () => (cards || []).map((card) => String(card?.id || '')).filter(Boolean),
    [cards],
  );

  useLayoutEffect(() => {
    if (!band?.registerCards) return undefined;
    band.registerCards(gridKey, cards);
    return () => band.unregisterCards?.(gridKey);
  }, [band, gridKey, cards]);

  const api = useMemo(() => {
    if (!band) {
      return {
        selected: new Set(),
        click() {},
        cardsForDrag(card) { return [card]; },
      };
    }
    return {
      selected: band.selected,
      click(id, event) {
        band.click(id, event, ids);
      },
      cardsForDrag(card) {
        return band.cardsForDrag(card);
      },
    };
  }, [band, ids]);

  return (
    <CardSelectContext.Provider value={api}>
      <div className={contents ? 'card-select-host is-contents' : 'card-select-host'}>
        <div className={contents ? ['is-contents', className].filter(Boolean).join(' ') : className}>
          {children}
        </div>
      </div>
    </CardSelectContext.Provider>
  );
}

// solid/src/components/CardSelectGrid.jsx
import { createContext, createEffect, createMemo, createUniqueId, untrack, useContext } from 'solid-js';
import { cardSelected, clickCard, dragPayload, registerGridCards, unregisterGridCards } from '../lib/select-band.js';

const CardSelectContext = createContext(null);

/** The grid a tile sits in, or null outside one (plain single-card links). */
export function useCardSelect() {
  return useContext(CardSelectContext);
}

/**
 * Marks a card grid for multi-select (market/src/components/CardSelectGrid.jsx).
 * The gestures live in lib/select-band*.js (installed once by Chrome); this
 * registers `cards` into the page-wide catalog so a drag pile can span every
 * rail on the page, and ranges Shift-clicks over this grid's ids. Same
 * wrapper markup as React so grid and rail CSS match.
 */
export default function CardSelectGrid(props) {
  const gridKey = createUniqueId();
  const ids = createMemo(() => (props.cards || []).map((card) => String(card?.id || '')).filter(Boolean));

  // Compute copies the list (tracking it); the catalog keeps the rows as
  // given — store-backed tiles stay live — read outside tracking.
  createEffect(
    () => [...(props.cards || [])],
    (cards) => {
      untrack(() => registerGridCards(gridKey, cards));
      return () => unregisterGridCards(gridKey);
    },
  );

  const api = {
    isSelected: (id) => cardSelected().has(String(id)),
    click(id, event) {
      clickCard(id, event, ids());
    },
    dragPayload,
  };

  return (
    <CardSelectContext value={api}>
      <div class={props.contents ? 'card-select-host is-contents' : 'card-select-host'}>
        <div class={props.contents ? ['is-contents', props.class ?? 'grid'] : (props.class ?? 'grid')}>
          {props.children}
        </div>
      </div>
    </CardSelectContext>
  );
}
