// market/src/components/ChatListingTag.jsx
import { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { fetchCard, fetchListings, imageSrc } from '../api.js';
import { fetchCardTiles } from '../lists.js';
import { setChatTagStock } from '../chat-dock-store.js';
import {
  bundleOf,
  cardIdOf,
  chatImageSources,
  chatQty,
  isSellerCard,
  listedCopies,
  overListingStock,
  paintOwned,
  personListsCard,
  tagKey,
  writeCardOwned,
} from '../chat-listing.js';
import ChatBundle from './ChatBundle.jsx';
import QtyStepper from './QtyStepper.jsx';
import ThumbZoom from './ThumbZoom.jsx';
import { endTrayDrag, startTrayDrag } from '../tray-drag.js';

function unique(list) {
  const out = [];
  for (const item of list) {
    const value = String(item || '').trim();
    if (value && !out.includes(value)) out.push(value);
  }
  return out;
}

function urlsFromCard(card) {
  if (!card) return [];
  return unique([
    card.homepageImageUrl,
    card.tileImageUrl,
    card.homepage_image_url,
    card.heroImageUrl,
    card.imageUrl,
    card.gridImageUrl,
    card.image_url,
    imageSrc(card, 'grid'),
    imageSrc(card, 'hero'),
  ]);
}

/** Tiles miss some printings (Ancient Origins Meowth 219916). The card page still has the scan. */
async function loadCatalogImages(id) {
  const tiles = await fetchCardTiles([id]).catch(() => []);
  const tile = (tiles || []).find((item) => String(item?.id) === id) || tiles?.[0];
  const fromTiles = urlsFromCard(tile);
  if (fromTiles.length) return fromTiles;
  const page = await fetchCard(id).catch(() => null);
  return urlsFromCard(page?.card);
}

function stopControl(event) {
  event.preventDefault();
  event.stopPropagation();
}

function CardQuantity({ row, draft, onQty }) {
  const qty = chatQty(row?.qty);
  if (!draft) {
    if (row?.qty == null || row.qty === '') return null;
    return <span className="chat-qty-badge">{qty}</span>;
  }
  return (
    <QtyStepper
      qty={qty}
      max={99}
      onChange={(next) => onQty?.(tagKey(row), next)}
    />
  );
}

export default function ChatListingTag(props) {
  if (bundleOf(props.row)) {
    return <ChatBundle row={props.row} peer={props.peer} onRemove={props.onRemove} trayId={props.trayId} />;
  }
  return <CardTag {...props} />;
}

function CardTag({ row, onRemove, onQty, peer, me, trayId }) {
  const label = row.cardName || 'Card';
  const id = cardIdOf(row);
  const identity = `${row.imageUrl || ''}|${id}|${row.sellerUid || ''}|${row.seller || ''}`;
  const peerUid = peer?.uid || '';
  const peerName = peer?.username || '';
  const meUid = me?.uid || '';
  const meName = me?.username || '';
  const [step, setStep] = useState(0);
  const [catalog, setCatalog] = useState([]);
  const [failed, setFailed] = useState(false);
  const [painted, setPainted] = useState(false);
  const people = [
    { uid: peerUid, username: peerName },
    { uid: meUid, username: meName },
  ];
  const [owned, setOwned] = useState(() => paintOwned(row, id, people));

  useEffect(() => {
    setStep(0);
    setCatalog([]);
    setFailed(false);
    setPainted(false);
    setOwned(paintOwned(row, id, people));
  }, [identity, id, row.seller, row.sellerUid, row.imageUrl, peerUid, peerName, meUid, meName]);

  useEffect(() => {
    if (!id) return undefined;
    let live = true;
    const people = [
      { uid: peerUid, username: peerName },
      { uid: meUid, username: meName },
    ];
    loadCatalogImages(id).then((next) => {
      if (live && next.length) setCatalog(next);
    }).catch(() => {});
    const sellers = [
      { uid: row.sellerUid, username: row.seller },
      { uid: peerUid, username: peerName },
    ];
    fetchListings(id).then((data) => {
      if (!live) return;
      const copies = listedCopies(data?.listings, sellers, row.listingId);
      if (copies) setChatTagStock(tagKey(row), copies);
      if (!isSellerCard(row)) {
        const next = personListsCard(data?.listings, people) ? 'yes' : 'no';
        writeCardOwned(id, people, next);
        setOwned(next);
      }
    }).catch(() => {});
    return () => { live = false; };
  }, [id, identity, peerUid, peerName, meUid, meName, row.seller, row.sellerUid, row.imageUrl]);

  const list = unique([...chatImageSources(row), ...catalog]);
  const catalogKey = catalog.join('|');
  useEffect(() => {
    if (!catalogKey || !failed) return;
    const at = list.findIndex((item) => catalog.includes(item));
    if (at < 0) return;
    if ((!painted || failed) && step !== at) setStep(at);
  }, [catalogKey, painted, failed, step, list, catalog]);

  const src = list[Math.min(step, Math.max(list.length - 1, 0))] || '';
  const full = list.find((url) => /\.jpe?g(?:\?|$)/i.test(url)) || list[list.length - 1] || src;

  function onError() {
    if (step + 1 < list.length) setStep(step + 1);
    else setFailed(true);
  }

  const draft = Boolean(onRemove);
  const quantity = <CardQuantity row={row} draft={draft} onQty={onQty} />;
  const image = src ? (
    <ThumbZoom src={full} full alt={label}>
      <img
        src={src}
        alt=""
        draggable={false}
        onError={onError}
        onLoad={(event) => {
          const img = event.currentTarget;
          if (img.naturalWidth > 0 && img.naturalWidth < 24) onError();
          else setPainted(true);
        }}
      />
    </ThumbZoom>
  ) : <span className="chat-tag-ph" />;
  const trade = owned === 'no';
  const over = overListingStock(row.qty, row.stock);
  const canDragOut = draft && Boolean(trayId);
  return (
    <span
      className={`chat-tag${trade ? ' is-trade' : ''}${over ? ' is-overstock' : ''}`}
      draggable={canDragOut}
      onDragStart={canDragOut ? (event) => {
        event.stopPropagation();
        startTrayDrag(event, {
          tray: trayId,
          reference: row,
          remove: () => onRemove(tagKey(row)),
        });
      } : undefined}
      onDragEnd={canDragOut ? () => endTrayDrag() : undefined}
    >
      {row.path ? (
        <Link to={row.path} aria-label={label} draggable={false} onClick={(event) => event.stopPropagation()}>{image}</Link>
      ) : (
        <span className="chat-tag-body" role="img" aria-label={label}>{image}</span>
      )}
      {quantity}
      {onRemove ? (
        <button type="button" aria-label={`Remove ${label}`} onClick={() => onRemove(tagKey(row))}>×</button>
      ) : null}
    </span>
  );
}

// solid/src/components/ChatListingTag.jsx
import { createEffect, createMemo, createSignal, Show } from 'solid-js';
import { fetchCard, fetchListings, imageSrc } from '@market/api.js';
import { setChatTagStock } from '@market/chat-dock-store.js';
import {
  bundleOf,
  cardIdOf,
  chatImageSources,
  chatQty,
  isSellerCard,
  listedCopies,
  overListingStock,
  paintOwned,
  personListsCard,
  tagKey,
  writeCardOwned,
} from '@market/chat-listing.js';
import { fetchCardTiles } from '@market/lists.js';
import { CHAT_ZOOM_MAX_HEIGHT } from '@market/scan-thumb-zoom.js';
import { endTrayDrag, startTrayDrag } from '@market/tray-drag.js';
import ChatBundle from './ChatBundle.jsx';
import QtyStepper from './QtyStepper.jsx';
import ThumbZoom from './ThumbZoom.jsx';

function unique(list) {
  const out = [];
  for (const item of list) {
    const value = String(item || '').trim();
    if (value && !out.includes(value)) out.push(value);
  }
  return out;
}

function urlsFromCard(card) {
  if (!card) return [];
  return unique([
    card.homepageImageUrl,
    card.tileImageUrl,
    card.homepage_image_url,
    card.heroImageUrl,
    card.imageUrl,
    card.gridImageUrl,
    card.image_url,
    imageSrc(card, 'grid'),
    imageSrc(card, 'hero'),
  ]);
}

/** Tiles miss some printings (Ancient Origins Meowth 219916). The card page still has the scan. */
async function loadCatalogImages(id) {
  const tiles = await fetchCardTiles([id]).catch(() => []);
  const tile = (tiles || []).find((item) => String(item?.id) === id) || tiles?.[0];
  const fromTiles = urlsFromCard(tile);
  if (fromTiles.length) return fromTiles;
  const page = await fetchCard(id).catch(() => null);
  return urlsFromCard(page?.card);
}

function CardQuantity(props) {
  return (
    <Show
      when={props.draft}
      fallback={(
        <Show when={!(props.row?.qty == null || props.row.qty === '')}>
          <span class="chat-qty-badge">{chatQty(props.row?.qty)}</span>
        </Show>
      )}
    >
      <QtyStepper qty={chatQty(props.row?.qty)} max={99} onChange={(next) => props.onQty?.(tagKey(props.row), next)} />
    </Show>
  );
}

function CardTag(props) {
  const row = () => props.row;
  const label = () => row().cardName || 'Card';
  const id = () => cardIdOf(row());
  const people = () => [
    { uid: props.peer?.uid || '', username: props.peer?.username || '' },
    { uid: props.me?.uid || '', username: props.me?.username || '' },
  ];
  // Everything that names "this tag": a new card, seller or scan starts over.
  const identity = createMemo(() => [
    row().imageUrl || '', id(), row().sellerUid || '', row().seller || '',
    props.peer?.uid || '', props.peer?.username || '', props.me?.uid || '', props.me?.username || '',
  ].join('|'));
  const [step, setStep] = createSignal(() => (identity(), 0));
  const [catalog, setCatalog] = createSignal(() => (identity(), []));
  const [failed, setFailed] = createSignal(() => (identity(), false));
  const [painted, setPainted] = createSignal(() => (identity(), false));
  const [owned, setOwned] = createSignal(() => (identity(), paintOwned(row(), id(), people())));

  createEffect(
    () => [id(), identity()],
    ([cardId]) => {
      if (!cardId) return undefined;
      let live = true;
      const tag = row();
      const who = people();
      loadCatalogImages(cardId).then((next) => {
        if (live && next.length) setCatalog(next);
      }).catch(() => {});
      const sellers = [
        { uid: tag.sellerUid, username: tag.seller },
        { uid: props.peer?.uid || '', username: props.peer?.username || '' },
      ];
      fetchListings(cardId).then((data) => {
        if (!live) return;
        const copies = listedCopies(data?.listings, sellers, tag.listingId);
        if (copies) setChatTagStock(tagKey(tag), copies);
        if (!isSellerCard(tag)) {
          const next = personListsCard(data?.listings, who) ? 'yes' : 'no';
          writeCardOwned(cardId, who, next);
          setOwned(next);
        }
      }).catch(() => {});
      return () => {
        live = false;
      };
    },
  );

  const list = createMemo(() => unique([...chatImageSources(row()), ...catalog()]));
  // A broken scan falls through to the first catalogue image once that list lands.
  createEffect(
    () => [catalog().join('|'), painted(), failed(), step(), list()],
    ([catalogKey, isPainted, isFailed, at, urls]) => {
      if (!catalogKey || !isFailed) return;
      const first = urls.findIndex((item) => catalog().includes(item));
      if (first < 0) return;
      if ((!isPainted || isFailed) && at !== first) setStep(first);
    },
  );

  const src = () => list()[Math.min(step(), Math.max(list().length - 1, 0))] || '';
  const full = () => list().find((url) => /\.jpe?g(?:\?|$)/i.test(url)) || list()[list().length - 1] || src();

  function onError() {
    if (step() + 1 < list().length) setStep(step() + 1);
    else setFailed(true);
  }

  const draft = () => Boolean(props.onRemove);
  const canDragOut = () => draft() && Boolean(props.trayId);
  const image = () => (
    <Show when={src()} fallback={<span class="chat-tag-ph" />}>
      <ThumbZoom src={full()} full alt={label()} maxHeight={CHAT_ZOOM_MAX_HEIGHT}>
        <img
          src={src()}
          alt=""
          draggable="false"
          onError={onError}
          onLoad={(event) => {
            const img = event.currentTarget;
            if (img.naturalWidth > 0 && img.naturalWidth < 24) onError();
            else setPainted(true);
          }}
        />
      </ThumbZoom>
    </Show>
  );

  return (
    <span
      class={['chat-tag', { 'is-trade': owned() === 'no', 'is-overstock': overListingStock(row().qty, row().stock) }]}
      draggable={canDragOut() ? 'true' : 'false'}
      onDragStart={(event) => {
        if (!canDragOut()) return;
        event.stopPropagation();
        const tag = row();
        startTrayDrag(event, { tray: props.trayId, reference: tag, remove: () => props.onRemove(tagKey(tag)) });
      }}
      onDragEnd={() => {
        if (canDragOut()) endTrayDrag();
      }}
    >
      <Show
        when={row().path}
        fallback={<span class="chat-tag-body" role="img" aria-label={label()}>{image()}</span>}
      >
        <a href={row().path} aria-label={label()} draggable="false" onClick={(event) => event.stopPropagation()}>{image()}</a>
      </Show>
      <CardQuantity row={row()} draft={draft()} onQty={props.onQty} />
      <Show when={props.onRemove}>
        <button type="button" aria-label={`Remove ${label()}`} onClick={() => props.onRemove(tagKey(row()))}>×</button>
      </Show>
    </span>
  );
}

/** A card, listing or bundle attached to a chat message or draft (market/src/components/ChatListingTag.jsx). */
export default function ChatListingTag(props) {
  return (
    <Show
      when={bundleOf(props.row)}
      fallback={(
        <CardTag
          row={props.row}
          onRemove={props.onRemove}
          onQty={props.onQty}
          peer={props.peer}
          me={props.me}
          trayId={props.trayId}
        />
      )}
    >
      <ChatBundle row={props.row} peer={props.peer} onRemove={props.onRemove} trayId={props.trayId} />
    </Show>
  );
}
