// market/src/components/SearchTabs.jsx
import { SEARCH_TABS, normalizeSearchTab } from '../search-kind.js';

export default function SearchTabs({
  value = 'singles',
  onChange,
  counts = null,
  ariaLabel = 'Search type',
}) {
  const current = normalizeSearchTab(value);
  return (
    <div className="search-tabs" role="tablist" aria-label={ariaLabel}>
      {SEARCH_TABS.map((tab) => {
        const count = counts?.[tab.id];
        const selected = current === tab.id;
        return (
          <button
            key={tab.id}
            type="button"
            role="tab"
            id={`search-tab-${tab.id}`}
            aria-selected={selected}
            className={selected ? 'on' : undefined}
            onClick={() => onChange?.(tab.id)}
          >
            {tab.label}
            {Number.isFinite(count) ? (
              <em>{count.toLocaleString('en-US')}</em>
            ) : null}
          </button>
        );
      })}
    </div>
  );
}

// solid/src/components/SearchTabs.jsx
import { For, Show } from 'solid-js';
import { SEARCH_TABS, normalizeSearchTab } from '@market/search-kind.js';

/** Singles / Product / Users tabs (market/src/components/SearchTabs.jsx). */
export default function SearchTabs(props) {
  const current = () => normalizeSearchTab(props.value);
  return (
    <div class="search-tabs" role="tablist" aria-label={props.ariaLabel || 'Search type'}>
      <For each={SEARCH_TABS}>
        {(tab) => (
          <button
            type="button"
            role="tab"
            id={`search-tab-${tab.id}`}
            aria-selected={(current() === tab.id) ? 'true' : 'false'}
            class={{ on: current() === tab.id }}
            onClick={() => props.onChange?.(tab.id)}
          >
            {tab.label}
            <Show when={Number.isFinite(props.counts?.[tab.id])}>
              <em>{props.counts[tab.id].toLocaleString('en-US')}</em>
            </Show>
          </button>
        )}
      </For>
    </div>
  );
}
