// solid/src/components/Carousel.jsx
import { createEffect, For, Repeat, Show } from 'solid-js';
import { bindRailControls, stepRail } from '@market/rail-scroll.js';
import CardSelectGrid from './CardSelectGrid.jsx';
import CardTile from './CardTile.jsx';

export function SkeletonTile(props) {
  return (
    <div
      class={[props.layout === 'list' ? 'tile tile-skel tile-row' : 'tile tile-skel', { 'tile-cut tile-album': props.album }]}
      aria-hidden="true"
    >
      <span class="tile-art"><span class="tile-ph" /></span>
      <div class="tile-meta">
        <Show
          when={props.album}
          fallback={(
            // The real tile's line boxes (name, identity, price) around the bars, so a
            // rail that fills in keeps its height (market Carousel.jsx SkeletonTile).
            <>
              <strong><span class="skel-line skel-inline" /></strong>
              <em class="tile-id"><span class="skel-line skel-line-sm skel-inline" /></em>
              <Show when={props.layout !== 'list'}>
                <span class="price"><span class="skel-line skel-line-sm skel-inline" /></span>
              </Show>
            </>
          )}
        >
          <span class="skel-line skel-line-sm" />
        </Show>
      </div>
    </div>
  );
}

/**
 * Horizontal rail (market/src/components/Carousel.jsx). Tiles are keyed by
 * card identity, so a rail that gains cards (progressive paint, priced
 * refresh) only inserts or patches the changed tiles.
 */
export default function Carousel(props) {
  let scroller;
  const ready = () => Boolean(props.cards?.length);
  createEffect(
    () => [props.cards?.length || 0, props.placeholders || 0],
    () => bindRailControls(scroller),
  );
  return (
    <Show when={ready() || (props.placeholders || 0) > 0}>
      <section class="carousel">
        <div class="carousel-head">
          <div class="carousel-title">
            <h2>{props.title}</h2>
            <Show when={props.subtitle}><p>{props.subtitle}</p></Show>
          </div>
          <Show when={props.href}><a class="see-all" href={props.href}>See more →</a></Show>
        </div>
        <div class="rail-wrap">
          <button class="rail-prev" type="button" onClick={() => stepRail(scroller, -1)} aria-label="Previous">
            <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5"><path d="m15.75 19.5-7.5-7.5 7.5-7.5" /></svg>
          </button>
          <div class="rail-scroll" ref={(node) => { scroller = node; }}>
            <CardSelectGrid class="carousel-track">
              <Show when={ready()} fallback={<Repeat count={props.placeholders || 0}>{() => <SkeletonTile />}</Repeat>}>
                <For each={props.cards}>
                  {(card, index) => <CardTile card={card} rank={index()} eagerLimit={props.eagerLimit || 0} />}
                </For>
              </Show>
            </CardSelectGrid>
          </div>
          <button class="rail-next" type="button" onClick={() => stepRail(scroller, 1)} aria-label="Next">
            <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5"><path d="m8.25 4.5 7.5 7.5-7.5 7.5" /></svg>
          </button>
        </div>
      </section>
    </Show>
  );
}

// market/src/components/Carousel.jsx
import { useLayoutEffect, useRef } from 'react';
import { Link } from 'react-router-dom';
import CardSelectGrid from './CardSelectGrid.jsx';
import CardTile from './CardTile.jsx';
import { bindRailControls, stepRail } from '../rail-scroll.js';

export function SkeletonTile({ layout = 'grid', album = false }) {
  return (
    <div
      className={[
        layout === 'list' ? 'tile tile-skel tile-row' : 'tile tile-skel',
        album ? 'tile-cut tile-album' : '',
      ].filter(Boolean).join(' ')}
      aria-hidden="true"
    >
      <span className="tile-art"><span className="tile-ph" /></span>
      <div className="tile-meta">
        {album ? (
          <span className="skel-line skel-line-sm" />
        ) : (
          <>
            {/* The real tile's line boxes (name, identity, price) around the bars, so
                a rail that fills in keeps its height (no layout shift). */}
            <strong><span className="skel-line skel-inline" /></strong>
            <em className="tile-id"><span className="skel-line skel-line-sm skel-inline" /></em>
            {layout === 'list' ? null : <span className="price"><span className="skel-line skel-line-sm skel-inline" /></span>}
          </>
        )}
      </div>
    </div>
  );
}

export default function Carousel({ title, subtitle, cards, href, placeholders = 0, eagerLimit = 0 }) {
  const scroller = useRef(null);
  const ready = Boolean(cards?.length);

  useLayoutEffect(() => bindRailControls(scroller.current), [cards, placeholders, ready]);

  if (!ready && placeholders < 1) {
    return null;
  }

  function step(direction) {
    stepRail(scroller.current, direction);
  }

  return (
    <section className="carousel">
      <div className="carousel-head">
        <div className="carousel-title">
          <h2>{title}</h2>
          {subtitle ? <p>{subtitle}</p> : null}
        </div>
        {href ? <Link className="see-all" to={href}>See more →</Link> : null}
      </div>
      <div className="rail-wrap">
        <button className="rail-prev" type="button" onClick={() => step(-1)} aria-label="Previous">
          <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5"><path d="m15.75 19.5-7.5-7.5 7.5-7.5" /></svg>
        </button>
        <div className="rail-scroll" ref={scroller}>
          <CardSelectGrid className="carousel-track" cards={ready ? cards : []}>
            {ready
              ? cards.map((card, index) => (
                  <CardTile key={card.id} card={card} rank={index} eagerLimit={eagerLimit} />
                ))
              : Array.from({ length: placeholders }, (_, index) => (
                  <SkeletonTile key={index} />
                ))}
          </CardSelectGrid>
        </div>
        <button className="rail-next" type="button" onClick={() => step(1)} aria-label="Next">
          <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5"><path d="m8.25 4.5 7.5 7.5-7.5 7.5" /></svg>
        </button>
      </div>
    </section>
  );
}
