// solid/src/components/DumpNav.jsx
import { For } from 'solid-js';
import { useLocation } from '@solidjs/router';

const LINKS = [
  { to: '/marketplace/explore', label: 'Explore', match: (path) => path.startsWith('/marketplace/explore') },
  { to: '/marketplace/portfolio', label: 'Portfolio', match: (path) => path.startsWith('/marketplace/portfolio') },
];

/** Explore / Portfolio tabs (market/src/components/DumpNav.jsx). */
export default function DumpNav() {
  const location = useLocation();
  return (
    <nav class="comp-tabs" aria-label="Market holdings">
      <For each={LINKS}>
        {(row) => <a class={row.match(location.pathname) ? 'on' : undefined} href={row.to}>{row.label}</a>}
      </For>
    </nav>
  );
}

// market/src/components/DumpNav.jsx
import { Link, useLocation } from 'react-router-dom';

const LINKS = [
  { to: '/marketplace/explore', label: 'Explore', match: (path) => path.startsWith('/marketplace/explore') },
  { to: '/marketplace/portfolio', label: 'Portfolio', match: (path) => path.startsWith('/marketplace/portfolio') },
];

export default function DumpNav() {
  const location = useLocation();
  return (
    <nav className="comp-tabs" aria-label="Market holdings">
      {LINKS.map((row) => (
        <Link key={row.to} className={row.match(location.pathname) ? 'on' : undefined} to={row.to}>
          {row.label}
        </Link>
      ))}
    </nav>
  );
}
