// solid/src/components/ExpansionMark.jsx
import { createSignal, Show } from 'solid-js';
import { setSlug } from '@market/api.js';
import { setAbbrev } from '@market/identity.js';
import { cdnFetchUrl } from '@market/image-urls.js';
import { expansionCode, expansionSymbolSrc } from '@market/set-logos.js';

/**
 * Circular expansion mark, or the letter code when the PNG is missing
 * (market/src/components/ExpansionMark.jsx). Loads from cdn.pokoin.com
 * directly: /card-images/* is a zone 301 to the CDN, one redirect per symbol.
 */
export default function ExpansionMark(props) {
  const slug = () => setSlug(props.setName);
  const src = () => cdnFetchUrl(expansionSymbolSrc({ slug: slug(), expansionSymbolUrl: props.symbolUrl }));
  const [dead, setDead] = createSignal(() => (src(), false));
  const code = () => expansionCode({ slug: slug(), name: props.setName }) || setAbbrev(props.setName) || '●';
  return (
    <Show when={!dead() && src()} fallback={<span class="set-shortcut-code">{code()}</span>}>
      <img class="set-shortcut-sym" src={src()} alt="" onError={() => setDead(true)} />
    </Show>
  );
}

// market/src/components/ExpansionMark.jsx
import { useState } from 'react';
import { setSlug } from '../api.js';
import { setAbbrev } from '../identity.js';
import { cdnFetchUrl } from '../image-urls.js';
import { expansionCode, expansionSymbolSrc } from '../set-logos.js';

/** Circular / official expansion mark. Falls back to the letter code if the PNG is missing. */
export default function ExpansionMark({ setName, symbolUrl }) {
  const [dead, setDead] = useState(false);
  const slug = setSlug(setName);
  // cdn.pokoin.com directly: /card-images/* is a zone 301 (one redirect per symbol).
  const src = cdnFetchUrl(expansionSymbolSrc({ slug, expansionSymbolUrl: symbolUrl }));
  const code = expansionCode({ slug, name: setName }) || setAbbrev(setName) || '●';
  if (dead || !src) {
    return <span className="set-shortcut-code">{code}</span>;
  }
  return (
    <img
      className="set-shortcut-sym"
      src={src}
      alt=""
      onError={() => setDead(true)}
    />
  );
}
