// solid/src/components/SeoHead.jsx
import { createEffect } from 'solid-js';
import { applySeoHead } from '@market/seo-head.js';

/** Head tags for the current page (market/src/seo-head.js, shared with React). */
export default function SeoHead(props) {
  createEffect(
    () => ({
      title: props.title,
      description: props.description,
      canonical: props.canonical,
      noindex: Boolean(props.noindex),
      image: props.image,
      imageAlt: props.imageAlt,
      jsonLd: props.jsonLd || null,
    }),
    (head) => applySeoHead(head),
  );
  return null;
}

// market/src/components/SeoHead.jsx
import { useEffect } from 'react';
import { applySeoHead } from '../seo-head.js';

export default function SeoHead({
  title,
  description,
  canonical,
  noindex = false,
  image,
  imageAlt,
  jsonLd,
}) {
  const encodedLd = JSON.stringify(jsonLd || null);
  useEffect(() => applySeoHead({
    title,
    description,
    canonical,
    noindex,
    image,
    imageAlt,
    jsonLd: encodedLd ? JSON.parse(encodedLd) : null,
  }), [title, description, canonical, noindex, image, imageAlt, encodedLd]);
  return null;
}
