// solid/src/pages/Home.jsx
import { createMemo, createSignal, createStore, For, onSettled, reconcile, Repeat, Show, snapshot } from 'solid-js';
import {
  attachRecentsToHome,
  fetchCard,
  fetchCardTiles,
  fetchExpansion,
  fetchExpansions,
  fetchHome,
  fetchHomeRail,
  fillMissingLastMedianPrices,
  mergeHomeRail,
  setSlug,
  warmupSearchBar,
} from '@market/api.js';
import { ASSET_COVERAGE_LINE } from '@market/buyer-protection.js';
import { fetchRail, RAIL, tileHasName } from '@market/lists.js';
import { isSetDeskCard } from '@market/search-filters.js';
import { game, isPokemonGame } from '@market/game.js';
import { HOME_BROWSE_BLOCK, createEnglishBrowseState, fillEnglishBrowse } from '@market/home-browse.js';
import { readHomeVectorCache, scheduleHomeVectorCacheWrite } from '@market/home-cache.js';
import { tilePricePkn } from '@market/pkn.js';
import {
  pruneUnresolvedRecents,
  readRecentCardIds,
  readRecentTiles,
  rememberRecentTiles,
  syncRemoteRecentCardIds,
} from '@market/recents.js';
import { Action, track } from '@market/track.js';
import { isOriginDownError, publicErrorMessage } from '@market/working-page.js';
import CardSelectGrid from '../components/CardSelectGrid.jsx';
import CardTile from '../components/CardTile.jsx';
import Carousel, { SkeletonTile } from '../components/Carousel.jsx';
import PromoCarousel from '../components/PromoCarousel.jsx';
import SeoHead from '../components/SeoHead.jsx';
import { loadAuth } from '../stores/auth.js';
import { authSession } from '../stores/session.js';

// Same pure helpers as market/src/pages/Home.jsx.
function cardsForIds(cards, ids) {
  const byId = new Map((cards || []).map((card) => [String(card.id), card]));
  return (ids || []).map((id) => byId.get(String(id))).filter(tileHasName).filter(isSetDeskCard);
}

function spotlightBrowse(payload) {
  return cardsForIds(payload?.cards, payload?.sections?.spotlightIds);
}

function paintHome(payload, recentIds, extraCards = []) {
  return attachRecentsToHome(payload, recentIds, extraCards);
}

function localExtras(tiles = []) {
  return [...readRecentTiles(), ...tiles];
}

function seedHome(cached) {
  const ids = readRecentCardIds();
  const extras = localExtras();
  if (cached) return paintHome(cached, ids, extras);
  if (!extras.length) return null;
  return paintHome({ cards: [], sections: {} }, ids, extras);
}

function railsReady(payload) {
  const sections = payload?.sections || {};
  return Boolean(sections.newArrivalIds?.length || sections.bestSellerIds?.length || sections.featuredIds?.length);
}

function recentsNeedingTiles(payload, ids) {
  const byId = new Map((payload?.cards || []).map((card) => [String(card.id), card]));
  return (ids || []).filter((id) => {
    const card = byId.get(String(id));
    return !tileHasName(card) || tilePricePkn(card) == null;
  });
}

async function fillMissingRecents(payload, ids, already = []) {
  const first = paintHome(payload, ids, localExtras(already));
  const need = recentsNeedingTiles(first, ids);
  if (!need.length) return first;
  const tiles = await fetchCardTiles(need).catch(() => []);
  rememberRecentTiles(tiles);
  const filled = paintHome(payload, ids, localExtras([...already, ...tiles]));
  const still = recentsNeedingTiles(filled, ids).filter((id) => {
    const card = (filled.cards || []).find((row) => String(row.id) === String(id));
    return !tileHasName(card);
  });
  if (!still.length) return filled;
  const extras = await Promise.all(
    still.slice(0, 8).map((id) => fetchCard(id).then((row) => row?.card || null).catch(() => null)),
  );
  const hydrated = extras.filter(Boolean);
  rememberRecentTiles(hydrated);
  const next = paintHome(payload, ids, localExtras([...already, ...tiles, ...hydrated]));
  const resolved = (next.sections?.recentlySeenIds || []).filter((id) => {
    const card = (next.cards || []).find((row) => String(row.id) === String(id));
    return tileHasName(card);
  });
  if (resolved.length !== ids.length) {
    pruneUnresolvedRecents(resolved);
    return paintHome(payload, resolved, localExtras([...already, ...tiles, ...hydrated]));
  }
  return next;
}

/**
 * Marketplace landing (market/src/pages/Home.jsx). The home vector lives in a
 * store reconciled by card id: a priced refresh or a late rail patches the
 * tiles whose fields changed instead of re-rendering every rail.
 */
export default function Home() {
  const site = game();
  const englishBrowse = isPokemonGame();
  let payload = seedHome(readHomeVectorCache(site.id));
  const [home, setHome] = createStore({ cards: payload?.cards || [], sections: payload?.sections || {} });
  const [error, setError] = createSignal('');
  const [recentPending, setRecentPending] = createSignal((() => {
    const ids = readRecentCardIds();
    const seen = payload?.sections?.recentlySeenIds || [];
    return ids.length > 0 && seen.length < ids.length;
  })());
  const [browse, setBrowse] = createStore({ cards: [] });
  const [browseHasMore, setBrowseHasMore] = createSignal(englishBrowse);
  const [browseLoading, setBrowseLoading] = createSignal(englishBrowse);
  const [browseMoreBusy, setBrowseMoreBusy] = createSignal(false);
  // Every rail keeps its skeleton until ALL rail requests settle: hiding an empty
  // rail as soon as another one lands, then showing it again, shifted the page
  // whenever rails arrived out of order (React Home has the same latent CLS).
  const [railsSettled, setRailsSettled] = createSignal(Boolean(payload && railsReady(payload)));
  let browseState = null;
  let disposed = false;

  function commit(next) {
    payload = next;
    setHome((draft) => {
      reconcile(next?.cards || [], 'id')(draft.cards);
      draft.sections = next?.sections || {};
    });
  }

  function setBrowseCards(cards) {
    setBrowse((draft) => {
      reconcile(cards, 'id')(draft.cards);
    });
  }

  async function applyRailsVector(data) {
    if (disposed || !data) return null;
    scheduleHomeVectorCacheWrite(site.id, data);
    const painted = paintHome(data, readRecentCardIds(), localExtras());
    commit(painted);
    return painted;
  }

  async function loadPokemonRails() {
    let vector = payload && railsReady(payload)
      ? { source: 'pi', cards: payload.cards || [], sections: { ...(payload.sections || {}) } }
      : { source: 'pi', cards: [], sections: {} };
    let any = false;
    // Serialize merges so parallel rail responses cannot clobber each other.
    let paintChain = Promise.resolve();
    const paintRail = (rail) => {
      paintChain = paintChain.then(async () => {
        if (disposed || !rail?.cards?.length) return;
        any = true;
        vector = mergeHomeRail(vector, rail);
        await applyRailsVector(vector);
      });
      return paintChain;
    };
    await Promise.all([
      fetchHomeRail('newCards').then(paintRail),
      fetchHomeRail('bestSellers').then(paintRail),
      fetchHomeRail('spotlight').then(paintRail),
      fetchRail(RAIL.spotlight).then((rail) => paintRail(rail && { ...rail, sectionKey: 'spotlightIds', limit: 16 })),
    ]);
    await paintChain;
    setRailsSettled(true);
    if (!any) return fetchHome(readRecentCardIds());
    return vector;
  }

  async function loadHome() {
    try {
      const data = await (englishBrowse ? loadPokemonRails() : fetchHome(readRecentCardIds()));
      setRailsSettled(true);
      if (disposed) return;
      const painted = (await applyRailsVector(data)) || paintHome(data, readRecentCardIds(), localExtras());
      // Network-only warmup: the suggest engine loads on search intent, not here.
      warmupSearchBar({ engine: false });
      let next = painted;
      if (!recentsNeedingTiles(painted, readRecentCardIds()).length) {
        setRecentPending(false);
      } else {
        next = await fillMissingRecents(data, readRecentCardIds());
        if (disposed) return;
        commit(next);
        setRecentPending(false);
      }
      const priced = await fillMissingLastMedianPrices(next.cards || []);
      if (disposed) return;
      next = { ...next, cards: priced };
      scheduleHomeVectorCacheWrite(site.id, next);
      commit(next);
    } catch (err) {
      if (disposed) return;
      setError(isOriginDownError(err, err?.status, err?.message)
        ? 'Marketplace home failed.'
        : publicErrorMessage(err, 'Marketplace home failed.'));
      setRecentPending(false);
      setRailsSettled(true);
    }
  }

  /** Signed-in buyers also see recents from other devices (account history). */
  async function syncAccountRecents() {
    if (!authSession()?.uid) return;
    await loadAuth().catch(() => null);
    const ids = await syncRemoteRecentCardIds().catch(() => null);
    if (disposed || !ids || !payload) return;
    const next = paintHome(payload, ids, localExtras());
    commit(next);
    if (!ids.length || !recentsNeedingTiles(next, ids).length) {
      setRecentPending(false);
      return;
    }
    setRecentPending(true);
    const filled = await fillMissingRecents(payload || next, ids);
    if (disposed) return;
    const priced = await fillMissingLastMedianPrices(filled.cards || []);
    commit({ ...filled, cards: priced });
    setRecentPending(false);
  }

  async function loadEnglishBrowse() {
    try {
      const data = await fetchExpansions({ limit: 500 });
      if (disposed) return;
      browseState = createEnglishBrowseState(data.expansions || data.sets || []);
      const next = await fillEnglishBrowse(browseState, { fetchExpansionPage: fetchExpansion });
      if (disposed) return;
      const filled = next.cards.length ? next.cards : spotlightBrowse(payload);
      setBrowseCards(filled);
      setBrowseHasMore(next.hasMore && next.cards.length > 0);
      if (!filled.length) return;
      const priced = await fillMissingLastMedianPrices(filled);
      if (!disposed) setBrowseCards(priced);
    } catch (_) {
      if (disposed) return;
      const fallback = spotlightBrowse(payload);
      if (fallback.length) setBrowseCards(fallback);
      setBrowseHasMore(false);
    } finally {
      if (!disposed) setBrowseLoading(false);
    }
  }

  async function loadMoreEnglish() {
    if (!browseState || browseMoreBusy()) return;
    setBrowseMoreBusy(true);
    try {
      const next = await fillEnglishBrowse(browseState, { fetchExpansionPage: fetchExpansion });
      const shown = browse.cards.length;
      setBrowse((draft) => {
        draft.cards.push(...next.cards);
      });
      setBrowseHasMore(next.hasMore);
      const priced = await fillMissingLastMedianPrices(next.cards);
      const byId = new Map(priced.map((card) => [String(card.id), card]));
      setBrowseCards(snapshot(browse.cards).map((card) => byId.get(String(card.id)) || card));
      if (next.cards[0]) {
        track(Action.loadMore, next.cards[0], { query: 'home-english', resultCount: shown + next.cards.length });
      }
    } finally {
      setBrowseMoreBusy(false);
    }
  }

  onSettled(() => {
    loadHome();
    syncAccountRecents();
    if (englishBrowse) loadEnglishBrowse();
    return () => {
      disposed = true;
    };
  });

  const sections = createMemo(() => {
    const cards = home.cards;
    const ids = home.sections || {};
    const spotlight = cardsForIds(cards, ids.spotlightIds);
    return {
      recentlySeen: cardsForIds(cards, ids.recentlySeenIds).slice(0, 20),
      newCards: cardsForIds(cards, ids.newArrivalIds),
      bestSellers: cardsForIds(cards, ids.bestSellerIds),
      featured: cardsForIds(cards, ids.featuredIds),
      spotlight: spotlight.length ? spotlight : cards,
    };
  });

  const loading = () => !railsReady(home) && !error();
  const railPending = () => !railsSettled() && !error();
  const newSet = () => sections().newCards[0]?.set || sections().newCards[0]?.set_name;
  const mega = () => sections().newCards[0] || sections().spotlight[0] || browse.cards[0];
  const gridCards = () => (englishBrowse ? browse.cards : sections().spotlight);
  const gridLoading = () => (englishBrowse ? browseLoading() && !browse.cards.length : loading());

  return (
    <div class="page home" aria-busy={loading() || recentPending() ? 'true' : undefined}>
      <SeoHead
        title={site.title}
        description="Buy and sell Pokémon TCG cards in PKN. Browse Pokémon, sets, eras, artists, and listings."
        canonical="/marketplace"
        jsonLd={{
          '@context': 'https://schema.org',
          '@type': 'WebSite',
          name: 'Pokoin',
          url: 'https://pokoin.com/',
          potentialAction: {
            '@type': 'SearchAction',
            target: 'https://pokoin.com/marketplace/search?q={search_term_string}',
            'query-input': 'required name=search_term_string',
          },
        }}
      />
      <Show when={error()}><p class="status error">{error()}</p></Show>
      <Show when={site.features?.promoCarousel}><PromoCarousel /></Show>

      <Carousel
        title="Recently seen"
        cards={sections().recentlySeen}
        placeholders={recentPending() && !sections().recentlySeen.length ? 8 : 0}
        eagerLimit={6}
      />
      <Carousel
        title="New cards"
        cards={sections().newCards}
        href={newSet() ? `/marketplace/sets/${setSlug(newSet())}` : undefined}
        placeholders={!sections().newCards.length && railPending() ? 8 : 0}
        eagerLimit={8}
      />
      <Carousel
        title="Best sellers"
        cards={sections().bestSellers}
        placeholders={!sections().bestSellers.length && railPending() ? 8 : 0}
      />
      <Carousel
        title="Spotlight"
        cards={sections().featured}
        placeholders={!sections().featured.length && railPending() ? 8 : 0}
      />

      <a class="callout protect-callout" href="/protection">
        {ASSET_COVERAGE_LINE}
        <span>Buyer protection →</span>
      </a>

      <a class="callout" href="/mypokoin" onClick={() => track(Action.sell, mega() || { id: '703382', name: 'sell' })}>
        Sell your cards for PKN
        <span>Get started →</span>
      </a>

      <section>
        <div class="carousel-head">
          <h2>Marketplace</h2>
        </div>
        <CardSelectGrid class="grid" cards={gridLoading() ? [] : gridCards()}>
          <Show
            when={!gridLoading()}
            fallback={<Repeat count={englishBrowse ? HOME_BROWSE_BLOCK : 12}>{() => <SkeletonTile />}</Repeat>}
          >
            <For each={gridCards()}>
              {(card, index) => <CardTile card={card} rank={index()} eagerLimit={0} />}
            </For>
          </Show>
        </CardSelectGrid>
        <Show when={englishBrowse && browseHasMore()}>
          <button class="more" type="button" onClick={loadMoreEnglish} disabled={browseMoreBusy()}>
            {browseMoreBusy() ? 'Loading…' : 'Show more'}
          </button>
        </Show>
      </section>
    </div>
  );
}

// market/src/pages/Home.jsx
import { useEffect, useMemo, useRef, useState } from 'react';
import { Link } from 'react-router-dom';
import {
  attachRecentsToHome,
  fetchCard,
  fetchCardTiles,
  fetchExpansion,
  fetchExpansions,
  fetchHome,
  fetchHomeRail,
  fillMissingLastMedianPrices,
  mergeHomeRail,
  setSlug,
  warmupSearchBar,
} from '../api.js';
import { ASSET_COVERAGE_LINE } from '../buyer-protection.js';
import { fetchRail, RAIL, tileHasName } from '../lists.js';
import { isSetDeskCard } from '../search-filters.js';
import { useAuth } from '../auth.jsx';
import { game, isPokemonGame } from '../game.js';
import {
  HOME_BROWSE_BLOCK,
  createEnglishBrowseState,
  fillEnglishBrowse,
} from '../home-browse.js';
import { readHomeVectorCache, scheduleHomeVectorCacheWrite } from '../home-cache.js';
import { tilePricePkn } from '../pkn.js';
import { readRecentCardIds, readRecentTiles, rememberRecentTiles, pruneUnresolvedRecents, syncRemoteRecentCardIds } from '../recents.js';
import { Action, track } from '../track.js';
import { isOriginDownError, noteOriginDown, publicErrorMessage } from '../working-page.js';
import { framedByChromeExtension } from '../extension-auth-bridge.js';
import CardSelectGrid from '../components/CardSelectGrid.jsx';
import CardTile from '../components/CardTile.jsx';
import Carousel, { SkeletonTile } from '../components/Carousel.jsx';
import PromoCarousel from '../components/PromoCarousel.jsx';
import SeoHead from '../components/SeoHead.jsx';

function cardsForIds(cards, ids) {
  const byId = new Map((cards || []).map((card) => [String(card.id), card]));
  return (ids || []).map((id) => byId.get(String(id))).filter(tileHasName).filter(isSetDeskCard);
}

function spotlightBrowse(payload) {
  return cardsForIds(payload?.cards, payload?.sections?.spotlightIds);
}

function paintHome(payload, recentIds, extraCards = []) {
  return attachRecentsToHome(payload, recentIds, extraCards);
}

function localExtras(tiles = []) {
  return [...readRecentTiles(), ...tiles];
}

function seedHome(cached) {
  const ids = readRecentCardIds();
  const extras = localExtras();
  if (cached) {
    return paintHome(cached, ids, extras);
  }
  if (!extras.length) {
    return null;
  }
  return paintHome({ cards: [], sections: {} }, ids, extras);
}

function railsReady(payload) {
  const sections = payload?.sections || {};
  return Boolean(
    sections.newArrivalIds?.length
    || sections.bestSellerIds?.length
    || sections.featuredIds?.length,
  );
}

function recentsNeedingTiles(payload, ids) {
  const byId = new Map((payload?.cards || []).map((card) => [String(card.id), card]));
  return (ids || []).filter((id) => {
    const card = byId.get(String(id));
    return !tileHasName(card) || tilePricePkn(card) == null;
  });
}

async function fillMissingRecents(payload, ids, already = []) {
  const first = paintHome(payload, ids, localExtras(already));
  const need = recentsNeedingTiles(first, ids);
  if (!need.length) {
    return first;
  }
  const tiles = await fetchCardTiles(need).catch(() => []);
  rememberRecentTiles(tiles);
  const filled = paintHome(payload, ids, localExtras([...already, ...tiles]));
  const still = recentsNeedingTiles(filled, ids).filter((id) => {
    const card = (filled.cards || []).find((row) => String(row.id) === String(id));
    return !tileHasName(card);
  });
  if (!still.length) {
    return filled;
  }
  const extras = await Promise.all(
    still.slice(0, 8).map((id) => fetchCard(id).then((row) => row?.card || null).catch(() => null)),
  );
  const hydrated = extras.filter(Boolean);
  rememberRecentTiles(hydrated);
  const next = paintHome(payload, ids, localExtras([...already, ...tiles, ...hydrated]));
  // Ids that still have no name are not in this game — drop them from local history.
  const resolved = (next.sections?.recentlySeenIds || []).filter((id) => {
    const card = (next.cards || []).find((row) => String(row.id) === String(id));
    return tileHasName(card);
  });
  if (resolved.length !== ids.length) {
    pruneUnresolvedRecents(resolved);
    return paintHome(payload, resolved, localExtras([...already, ...tiles, ...hydrated]));
  }
  return next;
}

export default function Home() {
  const { ready } = useAuth();
  const site = game();
  const payloadRef = useRef(null);
  const [payload, setPayload] = useState(() => {
    const next = seedHome(readHomeVectorCache(site.id));
    payloadRef.current = next;
    return next;
  });
  const [error, setError] = useState('');
  const [recentPending, setRecentPending] = useState(() => {
    const ids = readRecentCardIds();
    const seen = payloadRef.current?.sections?.recentlySeenIds || [];
    return ids.length > 0 && seen.length < ids.length;
  });
  const englishBrowse = isPokemonGame();
  const browseRef = useRef(null);
  const [browseCards, setBrowseCards] = useState([]);
  const [browseHasMore, setBrowseHasMore] = useState(englishBrowse);
  const [browseLoading, setBrowseLoading] = useState(englishBrowse);
  const [browseMoreBusy, setBrowseMoreBusy] = useState(false);
  // Every rail keeps its skeleton until ALL rail requests settle. Hiding an empty
  // rail as soon as another one landed, then showing it again, shifted the page
  // whenever the rails arrived out of order.
  const [railsSettled, setRailsSettled] = useState(() => Boolean(payloadRef.current && railsReady(payloadRef.current)));

  function commit(next) {
    payloadRef.current = next;
    setPayload(next);
  }

  useEffect(() => {
    document.title = site.title;
    let cancelled = false;
    const localIds = readRecentCardIds();
    const seen = payloadRef.current?.sections?.recentlySeenIds || [];
    setRecentPending(localIds.length > 0 && seen.length < localIds.length);

    // Three dedicated Rust rails paint as each arrives. Do not wait on Firebase.
    async function applyRailsVector(data) {
      if (cancelled || !data) {
        return null;
      }
      scheduleHomeVectorCacheWrite(site.id, data);
      const ids = readRecentCardIds();
      const painted = paintHome(data, ids, localExtras());
      commit(painted);
      return painted;
    }

    async function loadPokemonRails() {
      let vector = payloadRef.current && railsReady(payloadRef.current)
        ? { source: 'pi', cards: payloadRef.current.cards || [], sections: { ...(payloadRef.current.sections || {}) } }
        : { source: 'pi', cards: [], sections: {} };
      let any = false;
      // Serialize merges so parallel rail responses cannot clobber each other.
      let paintChain = Promise.resolve();
      const paintRail = (rail) => {
        paintChain = paintChain.then(async () => {
          if (cancelled || !rail?.cards?.length) {
            return;
          }
          any = true;
          vector = mergeHomeRail(vector, rail);
          await applyRailsVector(vector);
        });
        return paintChain;
      };
      await Promise.all([
        fetchHomeRail('newCards').then(paintRail),
        fetchHomeRail('bestSellers').then(paintRail),
        fetchHomeRail('spotlight').then(paintRail),
        fetchRail(RAIL.spotlight).then((rail) => paintRail(rail && {
          ...rail,
          sectionKey: 'spotlightIds',
          limit: 16,
        })),
      ]);
      await paintChain;
      if (!cancelled) {
        setRailsSettled(true);
      }
      if (!any) {
        return fetchHome(localIds);
      }
      return vector;
    }

    const homePromise = isPokemonGame() ? loadPokemonRails() : fetchHome(localIds);
    homePromise
      .then(async (data) => {
        if (cancelled) {
          return;
        }
        setRailsSettled(true);
        const painted = (await applyRailsVector(data)) || paintHome(data, readRecentCardIds(), localExtras());
        warmupSearchBar();
        let next = painted;
        const ids = readRecentCardIds();
        if (!recentsNeedingTiles(painted, ids).length) {
          setRecentPending(false);
        } else {
          next = await fillMissingRecents(data, readRecentCardIds());
          if (cancelled) {
            return;
          }
          commit(next);
          setRecentPending(false);
        }
        const priced = await fillMissingLastMedianPrices(next.cards || []);
        if (cancelled) {
          return;
        }
        next = { ...next, cards: priced };
        scheduleHomeVectorCacheWrite(site.id, next);
        commit(next);
      })
      .catch((err) => {
        if (!cancelled) {
          setRailsSettled(true);
          if (isOriginDownError(err, err?.status, err?.message)) {
            setError('Marketplace home failed.');
            setRecentPending(false);
            return;
          }
          setError(publicErrorMessage(err, 'Marketplace home failed.'));
          setRecentPending(false);
        }
      });
    return () => {
      cancelled = true;
    };
  }, [site.id, site.title]);

  useEffect(() => {
    if (!ready) {
      return undefined;
    }
    let cancelled = false;
    syncRemoteRecentCardIds()
      .then(async (ids) => {
        if (cancelled) {
          return;
        }
        const current = payloadRef.current;
        if (!current) {
          return;
        }
        const next = paintHome(current, ids, localExtras());
        commit(next);
        if (!ids.length) {
          setRecentPending(false);
          return;
        }
        if (!recentsNeedingTiles(next, ids).length) {
          setRecentPending(false);
          return;
        }
        setRecentPending(true);
        const filled = await fillMissingRecents(payloadRef.current || next, ids);
        if (cancelled) {
          return;
        }
        const priced = await fillMissingLastMedianPrices(filled.cards || []);
        commit({ ...filled, cards: priced });
        setRecentPending(false);
      })
      .catch(() => {});
    return () => {
      cancelled = true;
    };
  }, [ready]);

  useEffect(() => {
    if (!englishBrowse) {
      return undefined;
    }
    let cancelled = false;
    (async () => {
      try {
        const data = await fetchExpansions({ limit: 500 });
        if (cancelled) {
          return;
        }
        browseRef.current = createEnglishBrowseState(data.expansions || data.sets || []);
        const next = await fillEnglishBrowse(browseRef.current, {
          fetchExpansionPage: fetchExpansion,
        });
        if (cancelled) {
          return;
        }
        const filled = next.cards.length ? next.cards : spotlightBrowse(payloadRef.current);
        setBrowseCards(filled);
        setBrowseHasMore(next.hasMore && next.cards.length > 0);
        if (!filled.length) {
          return;
        }
        const priced = await fillMissingLastMedianPrices(filled);
        if (cancelled) {
          return;
        }
        setBrowseCards(priced);
      } catch (_) {
        if (!cancelled) {
          const fallback = spotlightBrowse(payloadRef.current);
          if (fallback.length) {
            setBrowseCards(fallback);
          }
          setBrowseHasMore(false);
        }
      } finally {
        if (!cancelled) {
          setBrowseLoading(false);
        }
      }
    })();
    return () => {
      cancelled = true;
    };
  }, [englishBrowse]);

  async function loadMoreEnglish() {
    if (!browseRef.current || browseMoreBusy) {
      return;
    }
    setBrowseMoreBusy(true);
    try {
      const next = await fillEnglishBrowse(browseRef.current, {
        fetchExpansionPage: fetchExpansion,
      });
      setBrowseCards((current) => [...current, ...next.cards]);
      setBrowseHasMore(next.hasMore);
      const priced = await fillMissingLastMedianPrices(next.cards);
      const byId = new Map(priced.map((card) => [String(card.id), card]));
      setBrowseCards((current) => current.map((card) => byId.get(String(card.id)) || card));
      if (next.cards[0]) {
        track(Action.loadMore, next.cards[0], { query: 'home-english', resultCount: browseCards.length + next.cards.length });
      }
    } finally {
      setBrowseMoreBusy(false);
    }
  }

  const sections = useMemo(() => {
    const empty = {
      recentlySeen: [],
      newCards: [],
      bestSellers: [],
      featured: [],
      spotlight: [],
    };
    if (!payload) {
      return empty;
    }
    const cards = payload.cards || [];
    const ids = payload.sections || {};
    return {
      recentlySeen: cardsForIds(cards, ids.recentlySeenIds).slice(0, 20),
      newCards: cardsForIds(cards, ids.newArrivalIds),
      bestSellers: cardsForIds(cards, ids.bestSellerIds),
      featured: cardsForIds(cards, ids.featuredIds),
      spotlight: cardsForIds(cards, ids.spotlightIds).length
        ? cardsForIds(cards, ids.spotlightIds)
        : cards,
    };
  }, [payload]);

  const loading = !railsReady(payload) && !error;
  const railPending = !railsSettled && !error;
  const newSet = sections.newCards[0]?.set || sections.newCards[0]?.set_name;
  const mega = sections.newCards[0] || sections.spotlight[0] || browseCards[0];
  const recentPlaceholders = recentPending && !sections.recentlySeen.length ? 8 : 0;
  const gridCards = englishBrowse ? browseCards : sections.spotlight;
  const gridLoading = englishBrowse ? browseLoading && !browseCards.length : loading;
  const gridPlaceholders = englishBrowse ? HOME_BROWSE_BLOCK : 12;
  return (
    <div className="page home" aria-busy={loading || recentPending ? 'true' : undefined}>
      <SeoHead
        title={site.title}
        description="Buy and sell Pokémon TCG cards in PKN. Browse Pokémon, sets, eras, artists, and listings."
        canonical="/marketplace"
        jsonLd={{
          '@context': 'https://schema.org',
          '@type': 'WebSite',
          name: 'Pokoin',
          url: 'https://pokoin.com/',
          potentialAction: {
            '@type': 'SearchAction',
            target: 'https://pokoin.com/marketplace/search?q={search_term_string}',
            'query-input': 'required name=search_term_string',
          },
        }}
      />
      {error ? <p className="status error">{error}</p> : null}
      {site.features.promoCarousel ? <PromoCarousel /> : null}

      <Carousel
        title="Recently seen"
        cards={sections.recentlySeen}
        placeholders={recentPlaceholders}
        eagerLimit={6}
      />
      <Carousel
        title="New cards"
        cards={sections.newCards}
        href={newSet ? `/marketplace/sets/${setSlug(newSet)}` : undefined}
        placeholders={!sections.newCards.length && railPending ? 8 : 0}
        eagerLimit={8}
      />
      <Carousel
        title="Best sellers"
        cards={sections.bestSellers}
        placeholders={!sections.bestSellers.length && railPending ? 8 : 0}
      />
      <Carousel
        title="Spotlight"
        cards={sections.featured}
        placeholders={!sections.featured.length && railPending ? 8 : 0}
      />

      <Link className="callout protect-callout" to="/protection">
        {ASSET_COVERAGE_LINE}
        <span>Buyer protection →</span>
      </Link>

      <Link className="callout" to="/mypokoin" onClick={() => track(Action.sell, mega || { id: '703382', name: 'sell' })}>
        Sell your cards for PKN
        <span>Get started →</span>
      </Link>

      <section>
        <div className="carousel-head">
          <h2>Marketplace</h2>
        </div>
        <CardSelectGrid className="grid" cards={gridLoading ? [] : gridCards}>
          {gridLoading
            ? Array.from({ length: gridPlaceholders }, (_, index) => <SkeletonTile key={index} />)
            : gridCards.map((card, index) => (
                <CardTile key={card.id} card={card} rank={index} eagerLimit={0} />
              ))}
        </CardSelectGrid>
        {englishBrowse && browseHasMore ? (
          <button className="more" type="button" onClick={loadMoreEnglish} disabled={browseMoreBusy}>
            {browseMoreBusy ? 'Loading…' : 'Show more'}
          </button>
        ) : null}
      </section>
    </div>
  );
}
