// solid/src/pages/RarityHub.jsx
import { createSignal, createStore, For, Match, onSettled, reconcile, Repeat, Show, Switch, untrack } from 'solid-js';
import { useParams } from '@solidjs/router';
import { fetchSearch } from '@market/api.js';
import { rarityMatches } from '@market/browse-hubs.js';
import { RARITY_HUBS, rarityFromSlug, rarityHref } from '@market/seo.js';
import CardSelectGrid from '../components/CardSelectGrid.jsx';
import CardTile from '../components/CardTile.jsx';
import { SkeletonTile } from '../components/Carousel.jsx';
import { Alert, EmptyDesk, PageHead } from '../components/Desk.jsx';
import SeoCrumbs from '../components/desk/SeoCrumbs.jsx';
import SeoHead from '../components/SeoHead.jsx';

function RarityIndex(props) {
  return (
    <div class="page desk hub-page">
      <SeoHead
        title="Pokémon Card Rarities | Pokoin"
        description="Browse Pokémon TCG cards by rarity: Common, Illustration Rare, Special Illustration Rare, Full-Art, Promo, and more."
        canonical={`/marketplace/${props.lang}/rarities`}
      />
      <SeoCrumbs items={[
        { name: 'Marketplace', href: '/marketplace' },
        { name: 'Rarities' },
      ]} />
      <PageHead kicker="Catalog" title="Rarities" />
      <ol class="hub-index hub-index-wide">
        <For each={RARITY_HUBS}>
          {(row) => (
            <li>
              <a href={rarityHref(row.slug, props.lang)}>{row.name}</a>
            </li>
          )}
        </For>
      </ol>
    </div>
  );
}

/** One rarity's printings: a card search for the rarity name, kept to rows of that rarity. */
function RarityCards(props) {
  const hub = untrack(() => props.hub);
  const lang = untrack(() => props.lang);
  const [list, setList] = createStore({ cards: [] });
  const [ready, setReady] = createSignal(false);
  const [error, setError] = createSignal('');
  let disposed = false;
  fetchSearch({ query: hub.name, limit: 48, lang, productType: 'card' })
    .then((data) => {
      if (disposed) return;
      setList((draft) => {
        reconcile((data.cards || []).filter((card) => rarityMatches(card, hub)), 'id')(draft.cards);
      });
      setReady(true);
      setError('');
    })
    .catch((err) => {
      if (!disposed) setError(err.message || 'Rarity cards failed.');
    });
  onSettled(() => () => {
    disposed = true;
  });

  return (
    <div class="page desk hub-page">
      <SeoHead
        title={`${hub.name} Pokémon Cards | Pokoin`}
        description={`${hub.name} Pokémon TCG printings on Pokoin. Compare sets, languages, and listings.`}
        canonical={rarityHref(hub.slug, lang)}
      />
      <SeoCrumbs items={[
        { name: 'Marketplace', href: '/marketplace' },
        { name: 'Rarities', href: `/marketplace/${lang}/rarities` },
        { name: hub.name },
      ]} />
      <PageHead kicker="Rarity" title={hub.name} />
      <p class="result-count">
        <Show when={ready()} fallback="Loading…">
          <strong>{list.cards.length}</strong> cards
        </Show>
      </p>
      <Alert message={error()} />
      <Show
        when={!(ready() && !list.cards.length)}
        fallback={<EmptyDesk title="No cards in this rarity" lede="Try another rarity or open a set desk." />}
      >
        <CardSelectGrid class="grid" cards={ready() ? list.cards : []}>
          <Show when={ready()} fallback={<Repeat count={12}>{() => <SkeletonTile />}</Repeat>}>
            <For each={list.cards}>
              {(card, index) => <CardTile card={card} rank={index()} />}
            </For>
          </Show>
        </CardSelectGrid>
      </Show>
    </div>
  );
}

/** /marketplace/:lang/rarities(/:slug) (market/src/pages/RarityHub.jsx). */
export default function RarityHub() {
  const params = useParams();
  const lang = () => params.lang || 'en';
  const hub = () => (params.slug ? rarityFromSlug(params.slug) : null);
  return (
    <Switch>
      <Match when={!params.slug}><RarityIndex lang={lang()} /></Match>
      <Match when={!hub()}>
        <div class="page desk hub-page">
          <EmptyDesk title="Unknown rarity" lede="Open the rarity index.">
            <a class="btn" href={`/marketplace/${lang()}/rarities`}>Rarities</a>
          </EmptyDesk>
        </div>
      </Match>
      <Match when={hub() && `${lang()}:${hub().slug}`} keyed>
        {(key) => <RarityCards hub={rarityFromSlug(key.slice(key.indexOf(':') + 1))} lang={key.slice(0, key.indexOf(':'))} />}
      </Match>
    </Switch>
  );
}

// market/src/pages/RarityHub.jsx
import { useEffect, useMemo, useState } from 'react';
import { Link, useParams } from 'react-router-dom';
import { fetchSearch } from '../api.js';
import CardSelectGrid from '../components/CardSelectGrid.jsx';
import CardTile from '../components/CardTile.jsx';
import { SkeletonTile } from '../components/Carousel.jsx';
import { Alert, EmptyDesk, PageHead } from '../components/Desk.jsx';
import SeoCrumbs from '../components/SeoCrumbs.jsx';
import SeoHead from '../components/SeoHead.jsx';
import { rarityMatches } from '../browse-hubs.js';
import { RARITY_HUBS, rarityFromSlug, rarityHref } from '../seo.js';

function RarityIndex({ lang }) {
  return (
    <div className="page desk hub-page">
      <SeoHead
        title="Pokémon Card Rarities | Pokoin"
        description="Browse Pokémon TCG cards by rarity: Common, Illustration Rare, Special Illustration Rare, Full-Art, Promo, and more."
        canonical={`/marketplace/${lang}/rarities`}
      />
      <SeoCrumbs items={[
        { name: 'Marketplace', href: '/marketplace' },
        { name: 'Rarities' },
      ]} />
      <PageHead
        kicker="Catalog"
        title="Rarities"
      />
      <ol className="hub-index hub-index-wide">
        {RARITY_HUBS.map((row) => (
          <li key={row.slug}>
            <Link to={rarityHref(row.slug, lang)}>{row.name}</Link>
          </li>
        ))}
      </ol>
    </div>
  );
}

export default function RarityHub() {
  const { lang = 'en', slug } = useParams();
  const hub = slug ? rarityFromSlug(slug) : null;
  const [cards, setCards] = useState(null);
  const [error, setError] = useState('');

  useEffect(() => {
    if (!hub) {
      setCards(null);
      return undefined;
    }
    let cancelled = false;
    setCards(null);
    fetchSearch({ query: hub.name, limit: 48, lang, productType: 'card' })
      .then((data) => {
        if (cancelled) return;
        setCards((data.cards || []).filter((card) => rarityMatches(card, hub)));
        setError('');
      })
      .catch((err) => {
        if (!cancelled) setError(err.message || 'Rarity cards failed.');
      });
    return () => {
      cancelled = true;
    };
  }, [hub?.slug, lang]);

  const shown = useMemo(() => cards || [], [cards]);

  if (!slug) {
    return <RarityIndex lang={lang} />;
  }
  if (!hub) {
    return (
      <div className="page desk hub-page">
        <EmptyDesk title="Unknown rarity" lede="Open the rarity index.">
          <Link className="btn" to={`/marketplace/${lang}/rarities`}>Rarities</Link>
        </EmptyDesk>
      </div>
    );
  }

  const title = `${hub.name} Pokémon Cards | Pokoin`;
  const description = `${hub.name} Pokémon TCG printings on Pokoin. Compare sets, languages, and listings.`;
  return (
    <div className="page desk hub-page">
      <SeoHead
        title={title}
        description={description}
        canonical={rarityHref(hub.slug, lang)}
      />
      <SeoCrumbs items={[
        { name: 'Marketplace', href: '/marketplace' },
        { name: 'Rarities', href: `/marketplace/${lang}/rarities` },
        { name: hub.name },
      ]} />
      <PageHead kicker="Rarity" title={hub.name} />
      <p className="result-count">
        {cards == null ? 'Loading…' : <><strong>{shown.length}</strong> cards</>}
      </p>
      <Alert>{error}</Alert>
      {cards && !shown.length ? (
        <EmptyDesk title="No cards in this rarity" lede="Try another rarity or open a set desk." />
      ) : (
        <CardSelectGrid className="grid" cards={cards == null ? [] : shown}>
          {cards == null
            ? Array.from({ length: 12 }, (_, index) => <SkeletonTile key={index} />)
            : shown.map((card, index) => (
              <CardTile key={card.id} card={card} rank={index} />
            ))}
        </CardSelectGrid>
      )}
    </div>
  );
}
