// market/src/components/SeoCrumbs.jsx
import { Link } from 'react-router-dom';

export default function SeoCrumbs({ items = [] }) {
  const crumbs = (items || []).filter((item) => item && item.name);
  if (!crumbs.length) {
    return null;
  }
  return (
    <nav className="crumbs" aria-label="Breadcrumb">
      {crumbs.map((item, index) => {
        const last = index === crumbs.length - 1;
        return (
          <span key={`${item.name}-${index}`}>
            {index ? <span className="sep">/</span> : null}
            {!last && item.href ? (
              <Link to={item.href}>{item.name}</Link>
            ) : (
              <span className={last ? 'here' : undefined}>{item.name}</span>
            )}
          </span>
        );
      })}
    </nav>
  );
}

// solid/src/components/desk/SeoCrumbs.jsx
import { For, Show } from 'solid-js';

/** Breadcrumb trail (market/src/components/SeoCrumbs.jsx). */
export default function SeoCrumbs(props) {
  const crumbs = () => (props.items || []).filter((item) => item && item.name);
  return (
    <Show when={crumbs().length}>
      <nav class="crumbs" aria-label="Breadcrumb">
        <For each={crumbs()}>
          {(item, index) => {
            const last = () => index() === crumbs().length - 1;
            return (
              <span>
                <Show when={index()}><span class="sep">/</span></Show>
                <Show when={!last() && item.href} fallback={<span class={last() ? 'here' : undefined}>{item.name}</span>}>
                  <a href={item.href}>{item.name}</a>
                </Show>
              </span>
            );
          }}
        </For>
      </nav>
    </Show>
  );
}
